# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed4321_size512.pkl
# data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: True
checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uniform/SELECT_EPSILON-SELECT_LS+-ALL/ep22_model_rew=0.005784.ckpt
num_iters: 10000

# SET (two-opt)
# checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uniform/SELECT_EPSILON-SET-ALL/ep80(last)_model_rew=0.003390.ckpt
# LS
#checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uniform/SELECT_EPSILON-SELECT_LS-ALL/ep80(last)_model_rew=0.002205.ckpt

# general VecEnv cfg
env_cfg:
  share_memory: False
  fixed_dataset: False
  create_nbh_graph: True    # automatically set to False for FFEncoder
  k_nbh_frac: 16

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}
    k: 32
    cap: 50


# overrides for validation env
val_env_cfg:
  fixed_dataset: True
  data_file_path: data/CVRP/cvrp${graph_size}/data_val_seed123_size512_${coords_dist}.pt


tester_cfg:
  # overrides for test env
  test_env_cfg:
    fixed_dataset: True
    data_file_path: data/CVRP/cvrp${graph_size}/data_test_seed234_size1000_${coords_dist}.pt
