# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: "gm_unif_mixed"
weights_dist: "random_k_variant"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path:
normalize_data: True
checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uniform/SELECT_EPSILON-SELECT_LS+-ALL/ep22_model_rew=0.005784.ckpt
num_iters: 100


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    mu_sampling_dist: "normal"
    mu_sampling_params: [ 0, 1 ]
    sigma_sampling_dist: "uniform"
    sigma_sampling_params: [ 0.05, 0.1 ]
    n_components: [ 1, 10 ]
    uniform_fraction: [ 0.5, 9 ]
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    k: 32
    cap: 50
    n_depots: 1 #number of depots (default = 1)


# VecEnv cfg
env_cfg:
  share_memory: False
  fixed_dataset: False
  create_nbh_graph: True    # automatically set to False for FFEncoder
  k_nbh_frac: 16

# overrides for validation env
val_env_cfg:
  fixed_dataset: True
  data_file_path: data/CVRP/cvrp${graph_size}/data_val_seed123_size512_${coords_dist}.pt


tester_cfg:
  # overrides for test env
  test_env_cfg:
    fixed_dataset: True
    data_file_path: data/CVRP/cvrp${graph_size}/data_test_seed234_size1000_${coords_dist}.pt
