# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uchoa'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
# data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/E_R_6_seed123_size512.pt
normalize_data: True
checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uniform/SELECT_EPSILON-SELECT_LS+-ALL/ep22_model_rew=0.005784.ckpt
num_iters: 10000

# SET (two-opt)
# checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uchoa/SELECT_EPSILON-SET-ALL/ep12_model_rew=0.002473.ckpt
# LS
#checkpoint_load_path: models/NeuroLS/checkpoints/cvrp_100_uniform/SELECT_EPSILON-SELECT_LS-ALL/ep80(last)_model_rew=0.002205.ckpt
# LS+
# models/NeuroLS/checkpoints/cvrp_100_uchoa/SELECT_EPSILON-SELECT_LS+-ALL/ep29_model_rew=0.000629.ckpt

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    # if None in the following two args, then all are mixed
    depot_type:  # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type:  # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
    demand_type:   # if None demand will be generated uniformly at random
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}
    k: 100
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

# Model VecEnv cfg
env_cfg:
  share_memory: False
  fixed_dataset: False
  create_nbh_graph: True    # automatically set to False for FFEncoder
  k_nbh_frac: 16

# overrides for validation env
val_env_cfg:
  fixed_dataset: True
  data_file_path: data/val_data/cvrp/uchoa100_seed1234_size512.pt
  # data/CVRP/cvrp${graph_size}/data_val_seed123_size512_${coords_dist}.pt

# overrides for test env
tester_cfg:
  test_env_cfg:
    fixed_dataset: True
    data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
