# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/test_seed1234.pkl
normalize_data: True
checkpoint_load_path: models/NeuroLS/checkpoints/${problem}_${graph_size}_${coords_dist}/SELECT_EPSILON-SELECT_LS+-ALL/
num_iters: 100

# general VecEnv cfg
env_cfg:
  share_memory: False
  fixed_dataset: False
  create_nbh_graph: True    # automatically set to False for FFEncoder
  k_nbh_frac: 0.25

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}

# overwrites for validation env
val_env_cfg:
  fixed_dataset: True
  data_file_path: data/TSP/tsp${graph_size}/data_val_seed123_size512_${coords_dist}.pt


tester_cfg:
  # overwrites for test env
  test_env_cfg:
    fixed_dataset: True
    data_file_path: data/TSP/tsp${graph_size}/data_test_seed123_size512_${coords_dist}.pt
