# @package _global_
# problem args

problem: "cvrp"
graph_size:
coords_dist: 'uchoa'
out_name: ${problem}_X_${coords_dist}
data_file_path: data/test_data/cvrp/uchoa/X
normalize_data: True
checkpoint_load_path: models/AM/AM/pretrained/${problem}_100/${coords_dist}/epoch-99.pt
trained_model_args_path: models/AM/AM/pretrained/${problem}_100/${coords_dist}/args.json

# RP Env cfg
env_kwargs:
  generator_args:
  sampling_args: