# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: uniform
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/tsp100_test_seed1234.pkl
# data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/test_seed1234.pkl
normalize_data: True
checkpoint_load_path: models/SGBS/SGBS/${problem}/1_pre_trained_model/Saved_TSP${graph_size}_Model/${coords_dist}/checkpoint-2800.pt


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}

# Model Env cfg
env_cfg:
  problem_size: ${graph_size}
  pomo_size: ${tester_cfg.pomo_size}
  generator_args:
    coords_dist: ${coords_dist}
    graph_size: ${graph_size}