# @package _global_
# problem args

problem: "cvrp"
graph_size: 50
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path:
normalize_data: False
# checkpoint in model cfg yaml


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: #
  sampling_args:
    graph_size: ${graph_size}
    subsample: False
    num_samples: ${val_size}
    distribution: ${coords_dist}
