# @package _global_
# problem args

problem: "cvrp"
graph_size: 50
coords_dist: 'uchoa'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path:
normalize_data: False
# checkpoint in model cfg yaml


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: ${weights_dist}
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: #
    # if None in the following two args, then all are mixed
    depot_type: E # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type:  # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
    demand_type:   # if None demand will be generated uniformly at random
  sampling_args:
    sample_size: 512
    graph_size: ${graph_size}
    subsample: False
    k: 13
    cap: 40
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)
