# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: uchoa
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/uchoa/${problem}${graph_size}/val_seed1234_size128.pt
  # data/test_data/cvrp/sub_uniform/cvrp100/val_seed4321_size128.pt
# data/test_data/cvrp/uniform/cvrp100/val_seed4321_size512.pkl
normalize_data: True
# checkpoint_load_path: loaded in model cfg
k_sparse: 20
n_ants: 20

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance: # data/train_data/${problem}/${coords_dist}/single_large_instance.pt
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

