# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uchoa'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: True
checkpoint_load_path: models/MDAM/MDAM/pretrained/vrp_${graph_size}/uniform/epoch-99.pt # uniform ckpt better on uchoa

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    # if None in the following two args, then all are mixed
    depot_type: E # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type:  # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
    demand_type:   # if None demand will be generated uniformly at random
  sampling_args:
    sample_size: 512
    graph_size: ${graph_size}
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)