# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed4321_size512.pkl
normalize_data: True
checkpoint_load_path: models/MDAM/MDAM/pretrained/vrp_${graph_size}/${coords_dist}/epoch-99.pt

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist:
  sampling_args:
    graph_size: ${graph_size}
    num_samples: ${val_size}
    distribution: ${coords_dist}