# @package _global_
# problem args

problem: "cvrp"
graph_size:
coords_dist: 'uchoa'
XE_type: XE_1
out_name: ${problem}_${XE_type}_${coords_dist}
data_file_path: data/test_data/cvrp/uchoa/XE/${XE_type}
normalize_data: True
checkpoint_load_path: models/GLOP/GLOP/pretrained/Reviser-stage2 # /reviser_{reviser_size}/epoch-299.pt'
ckpt_path_partitioner: models/GLOP/GLOP/pretrained/Partitioner/cvrp/cvrp-100.pt
problem_type: ${problem}

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: random_int # sampling integers from 1-10
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance: data/train_data/${problem}/${coords_dist}/single_large_instance.pt
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)
