# @package _global_
# problem args

problem: "cvrp"
graph_size: 1000
coords_dist: "uniform"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/cvrp/uniform/cvrp1000/vrp1000_test_seed1234.pkl
normalize_data: True
checkpoint_load_path: models/GLOP/GLOP/pretrained/Reviser-stage2 # /reviser_{reviser_size}/epoch-299.pt'
ckpt_path_partitioner: models/GLOP/GLOP/pretrained/Partitioner/cvrp/cvrp-1000.pt
problem_type: ${problem}

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist: random_int # sampling integers from 1-10
    normalize_demands: False  # if None or False - demands will remain un-normalized (not between 0-1)
    single_large_instance:
  sampling_args:
    sample_size: 2 # 64
    graph_size: ${graph_size}
    subsample: False
    k: 150
    cap: 200
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

