# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: "uniform_fu"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/uniform/fu/tsp${graph_size}_fu.pt
  # data/test_data/cvrp/sub_uniform/cvrp100/val_seed4321_size128.pt
# data/test_data/cvrp/uniform/cvrp100/val_seed4321_size512.pkl
normalize_data: True
checkpoint_load_path: models/GLOP/GLOP/pretrained/Reviser-stage2 # /reviser_{reviser_size}/epoch-299.pt'
ckpt_path_partitioner: # for TSP no partitioner
problem_type: ${problem}

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: uniform
    single_large_instance: #
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False

