# @package _global_

# tensorboard --host localhost --port 8080 --logdir=./outputs

run_type: "train"
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
cuda: True  # False

train_cfg:
  get_val_set:
  val_dataset:
  val_size: 1000
  checkpoint_save_path: 'checkpoints/'
  save_dataset_object: True
  use_cuda: USE_CUDA
  cuda_device_num: 0
  epochs: 100 # 8100
  train_episodes: 10000  # 10 * 1000
  train_batch_size: 64
  prev_model_path: None
  optimizer_cfg:
    optimizer:
      lr: 1e-4
      weight_decay: 1e-5
    scheduler:
      milestones: [ 8001, 8051 ]
      gamma: 0.1
  logging:
    model_save_interval: 5 # 500
    img_save_interval: 500
    log_image_params_1:
      json_foldername: log_image_style
      filename: style_cvrp_20.json
    log_image_params_2:
      json_foldername: log_image_style
      filename: style_loss_1.json
  model_load:
    enable: False  # True  # enable loading pre-trained model
    path:  # directory path of pre-trained model and log files saved.
    epoch: 90  # epoch version of pre-trained model to laod.


# Model Env cfg
env_cfg:
  problem_size: ${graph_size}
  pomo_size: 100
  generator_args:
    coords_dist: ${coords_dist}
    graph_size: ${graph_size}


test_cfg:
  data_file_path: # None         # data/test_data/cvrp/uniform/cvrp20_test_seed1234.pkl
  checkpoint_load_path: #None
  saved_res_dir: #None

#tester_cfg:
#  cuda_device_num:
#  test_episodes: # 512  # 10000 # 10*1000  # as long as dataset --> handled internally in pomo.py
#  test_batch_size: # 1000
#  augmentation_enable: # False
#  aug_factor:  # 8
#  pomo_size: #  ${graph_size} # or 1 (single trajectory)
#  aug_batch_size: # 400  # note: needs to be divisble by number of test instances -> 400 only for 10000

# model-specific test_cfg
tester_cfg:
  cuda_device_num: 0
  test_episodes: 1 # 512  # 10000 # 10*1000  # as long as dataset --> handled internally in pomo.py
  test_batch_size: 1 # 1000
  augmentation_enable: False
  aug_factor: 8
  pomo_size: ${graph_size} # or 1 (single trajectory)
  aug_batch_size: 400  # note: needs to be divisble by number of test instances -> 400 only for 10000



# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
logger_cfg:
  log_file:
  desc: 'logs_i/'  # train_${problem}_n${graph_size}_with_${coords_dist}
log_path: 'logs/'
checkpoint_save_path: 'checkpoints/'
checkpoint_load_path: '/home/thyssens/git/Research/L2O/routing-arena/models/POMO/POMO/cvrp/POMO/result/saved_ckpts/checkpoint-90.pt'
#models/POMO/POMO/${problem}/result/Saved_CVRP100_Model/ACTOR_state_dic.pt
#models/POMO/POMO/cvrp/result/Saved_CVRP100_Model/ACTOR_state_dic.pt
