# @package _global_
# problem args

problem: "cvrp"
graph_size:
coords_dist: 'golden'
out_name: ${problem}_${coords_dist}
data_file_path: data/test_data/cvrp/Golden
normalize_data: True
checkpoint_load_path: models/EAS/EAS/trained_models/XE_1/ACTOR_state_dic.pt

# RP Env cfg
env_kwargs:
  generator_args:
    normalize_demands: True  # if None or False - demands will remain un-normalized (not between 0-1)
  sampling_args:
