# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/uniform/tsp100/test_seed1234.pkl
normalize_data: True

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance:
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    subsample: False
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)