# @package _global_
# model parameters

# POLICY model
# policy_cfg:
#  embedding_dim: 128
model: "BQ"

# model params
model_cfg:
  dim_emb: 192
  dim_ff: 512
  nb_layers_encoder: 9
  nb_heads: 12
  dropout: 0.0
  batchnorm: False
  activation_ff: relu
  activation_attention: softmax