# @package _global_

# tensorboard --host localhost --port 8080 --logdir=./outputs

run_type: "val"
number_runs: 1
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
cuda: True
# eGPU GeForce RTX 3060 (G3DMark Mark: 17177, G2DMark: 975)
G3DMark: 17177
G2DMark: 975
# DELL Machine (Intel® Core™ i7-10850H - 12 Threads): 11980
# DELL Machine (Intel® Core™ i7-10850H - 1 Threads): 2714
CPU_Mark_single: 2714
CPU_Mark: 11980
number_threads: 12
number_cpus: 6

test_cfg:
  eval_type: ['pi', 'wrap']  # 'simple', 'wrap', 'pi', ['pi', 'wrap']
  time_limit: 10
  save_solutions: True   # either save solution in log dir of run output dir
  save_for_analysis: False  # or save solutions for further analysis in saved results folder
  saved_res_dir: outputs/saved_results # where results for analysis should be saved
  out_name: ${out_name}
  save_trajectory: True   # will always be saved in log dir of run output dir
  save_traj_for:  # IDs of Instances to plot in list - if None, first instance in dataset is plotted
  fixed_dataset: True
  data_file_path: ${data_file_path}
  checkpoint_load_path: ${checkpoint_load_path}
  dataset_size:  # to overwrite the number of instances to be tested in fixed test set (first 5 instances)
  dataset_range: # solve range of dataset , e.g. [10, 20]
  add_ls: False # True  # boolean to add local search (spec in 'ls_policy_cfg') after construction
  ls_policy: sa
  ls_policy_cfg:
    local_search_strategy: 'SIMULATED_ANNEALING' #'SIMULATED_ANNEALING' #'GUIDED_LOCAL_SEARCH'
    solution_limit: #None
    verbose: False
    log_search: False
    batch_size: 1
    search_workers: 1  # only possible to parallelize search if cp_sat solver is enabled in GORT LS

# model-specific test_cfg
tester_cfg:
  problem: ${problem}
  method: ${model} # which type of search: sampling, eas-emb, eas-lay, or eas-tab
  nb_instances: ${tester_cfg.dataset_size}
  round_distances: False  # Round distances to the nearest integer. Required to solve .vrp instances
  instances_offset: 0
  max_iter: 1000000  # Maximum number of EAS iterations
  max_runtime: ${test_cfg.time_limit}  # 100000 # Maximum runtime of EAS per batch in seconds
  batch_size: 1  # default for eas is 25  # Set to 1 for single instance search
  p_runs: 1    # If batch_size is 1, set this to > 1 to do multiple runs for the instance in parallel
  param_lambda: 0.013  # EAS-Emb and EAS-Lay parameters
  param_lr: 0.0041  # EAS-Emb and EAS-Lay parameters
  param_alpha: 0.539  # EAS-Tab parameters
  param_sigma: 9.55   # EAS-Tab parameters
  output_path:

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'
checkpoint_save_path: 'checkpoints/'

