# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: "uniform"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/cvrp/uniform/cvrp100/val_seed4321_size512.pkl
normalize_data: True
checkpoint_load_path: models/POMO/POMO/${problem}/POMO/result/saved_CVRP100_model/${coords_dist}/checkpoint-30500.pt


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    weights_sampling_dist:
  sampling_args:
    sample_size: 64
    graph_size: ${graph_size}
    k: 16
    cap: 50
    max_cap_factor: # factor of additional capacity w.r.t. a norm capacity of 1.0 per vehicle
    n_depots: 1 #number of depots (default = 1)

# Model Env cfg
env_cfg:
  problem_size: ${graph_size}
  pomo_size: ${tester_cfg.pomo_size}
  generator_args:
    coords_dist: ${coords_dist}
    graph_size: ${graph_size}