# @package _global_
# problem args

problem: "cvrp"
graph_size: 100
coords_dist: 'XML'
# ...
out_name: ${problem}_${graph_size}_${coords_dist}
# after download is finished:
  # - rename the folder from Vrp-Set-XML100 to XML100
  # - data_file_path below should change to data/test_data/cvrp/XML100/instances
data_file_path: data/test_data/cvrp/XML100/subsampled/instances
normalize_data: True
checkpoint_load_path: models/POMO/POMO/${problem}/POMO/result/saved_CVRP100_model/uchoa/checkpoint-8100.pt


# RP Env cfg
env_kwargs:
  generator_args:
  sampling_args:


# Model Env cfg
env_cfg:
  problem_size: ${graph_size}
  pomo_size: ${tester_cfg.pomo_size}
  generator_args:
    coords_dist: ${coords_dist}
    graph_size: ${graph_size}