# @package _global_
# problem args

# @package _global_
# problem args

problem: "cvrp"
graph_size: 50
coords_dist: 'uniform'
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/val_seed123_size512.pt
normalize_data: True

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}
    k: 8
    cap: 40