# @package _global_
# problem args

problem: "tsp"
graph_size: 
coords_dist: "tsplib"
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/tsplib/raw_data
normalize_data: True

# RP Env cfg
env_kwargs:
  generator_args:
  sampling_args:
    # sample_size: 1
    graph_size: ${graph_size}

