# @package _global_

# tensorboard --host localhost --port 8080 --logdir=./outputs

run_type: "val"
number_runs: 1
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
cuda: True
# eGPU GeForce RTX 3060 (G3DMark Mark: 17177, G2DMark: 975)
G3DMark: 17177
G2DMark: 975
# DELL Machine (Intel® Core™ i7-10850H - 12 Threads): 11980
# DELL Machine (Intel® Core™ i7-10850H - 1 Threads): 2714
CPU_Mark_single: 2714
CPU_Mark: 11980
number_threads: 12
number_cpus: 6

test_cfg:
  eval_type: ['pi', 'wrap']  # 'simple', 'wrap', 'pi', ['pi', 'wrap']
  time_limit: 10
  save_solutions: False   # either save solution in log dir of run output dir
  save_for_analysis: False # or save solutions for further analysis in saved results folder
  saved_res_dir: outputs/saved_results # where results for analysis should be saved
  out_name: ${out_name}
  save_trajectory: True   # will always be saved in log dir of run output dir
  save_traj_for:  # IDs of Instances to plot in list - if None, first instance in dataset is plotted
  fixed_dataset: True
  dataset_size:   # to overwrite the number of instances to be tested in fixed test set (first 5 instances)
  dataset_range:  # list of the dataset range to be tested for e.g. [10, 50]
  data_file_path: ${data_file_path} # depends on distribution --> env config
  checkpoint_load_path: ${checkpoint_load_path}
  batch_size: 1
  decode_type: 'greedy'  # 'sample'
  sample_size: 0         # if select sample as decode strategy, default is 1280 - else disable and set to 0
  eval_batch_size: 1
  add_ls: False # True  # boolean to add local search (spec in 'ls_policy_cfg') after construction
  ls_policy_cfg:
    local_search_strategy: 'SIMULATED_ANNEALING' #'SIMULATED_ANNEALING' #'GUIDED_LOCAL_SEARCH'
    solution_limit: #None
    verbose: False
    advanced_search_operators: True
    log_search: False
    batch_size: 1
    search_workers: 1  # only possible to parallelize search if cp_sat solver is enabled in GORT LS

#    time_limit: ${test_cfg.time_limit} #4
# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'
checkpoint_save_path: 'checkpoints/'


