# @package _global_

# tensorboard --host localhost --port 8080 --logdir=./outputs

run_type: "val"
number_runs: 1
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
cuda: True
# eGPU GeForce RTX 3060 (G3DMark Mark: 17177, G2DMark: 975)
G3DMark: 17177
G2DMark: 975
# DELL Machine (Intel® Core™ i7-10850H - 12 Threads): 11980
# DELL Machine (Intel® Core™ i7-10850H - 1 Threads): 2714
CPU_Mark_single: 2714
CPU_Mark: 11980
number_threads: 12
number_cpus: 6

test_cfg:
  eval_type: ['pi', 'wrap']  # 'simple', 'wrap', 'pi', ['pi', 'wrap']
  time_limit: 10
  save_solutions: True   # either save solution in log dir of run output dir
  save_for_analysis: False # or save solutions for further analysis in saved results folder
  saved_res_dir: outputs/saved_results # where results for analysis should be saved
  out_name: ${out_name}
  save_trajectory: True   # will always be saved in log dir of run output dir
  save_traj_for:  # IDs of Instances to plot in list - if None, first instance in dataset is plotted
  fixed_dataset: True
  data_file_path: ${data_file_path} # depends on distribution --> env config
  dataset_range:  # list of the dataset range to be tested for e.g. [10, 50]
  dataset_size: # to overwrite the number of instances to be tested in fixed test set (first 5 instances)
  checkpoint_load_path: ${checkpoint_load_path}
  beam: 16              # 1 = 'greedy', 30 = 30 copies of backtracking, 50 = 50 copies of backtracking
  eval_batch_size: 1
  add_ls: False # True  # boolean to add local search (spec in 'ls_policy_cfg') after construction
  ls_policy_cfg:
    local_search_strategy: 'SIMULATED_ANNEALING' #'SIMULATED_ANNEALING' #'GUIDED_LOCAL_SEARCH'
    solution_limit: #None
    verbose: False
    log_search: False
    batch_size: 1
    search_workers: 1  # only possible to parallelize search if cp_sat solver is enabled in GORT LS


# important model run options
# eval options
eval_opts_cfg:
  test_only: True
  knns: -1                                       # Number of KNNs used during the decoding" (default -1)
  # seed: 0
  beam_size: ${test_cfg.beam}                   # default 1
  val_batch_size: ${test_cfg.eval_batch_size}   # default 1024
  test_batch_size: ${test_cfg.eval_batch_size}  # default 1024
  val_dataset:                                  # only in train
  train_dataset:                                # only in train
  test_dataset: None                            # loaded from RA not file path
  debug:
  output_dir:

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'
checkpoint_save_path: 'checkpoints/'


