# @package _global_

# tensorboard --host localhost --port 8080 --logdir=./outputs

run_type: "test"
number_runs: 1 # 4
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
cuda: True
# eGPU GeForce RTX 3060 (G3DMark Mark: 17177, G2DMark: 975)
G3DMark: 17177
G2DMark: 975
# DELL Machine (Intel® Core™ i7-10850H - 12 Threads): 11980
# DELL Machine (Intel® Core™ i7-10850H - 1 Threads): 2714
CPU_Mark_single: 2714
CPU_Mark: 11980
number_threads: 12
number_cpus: 6

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
val_log_path: 'logs/val/'
test_log_path: 'logs/test/'
log_path: 'logs/'
checkpoint_save_path: 'checkpoints/'
#
test_cfg:
  eval_type: ['pi', 'wrap']  # 'simple', 'wrap', 'pi', ['pi', 'wrap']
  time_limit: 10
  save_solutions: False   # either save solution in log dir of run output dir
  save_for_analysis: True # or save solutions for further analysis in saved results folder
  saved_res_dir: outputs/saved_results # where results for analysis should be saved
  out_name: ${out_name}
  save_trajectory: True   # will always be saved in log dir of run output dir
  save_traj_for: # IDs of Instances to plot in list - if None, first instance in dataset is plotted
  dataset_size:  # to overwrite the number of instances to be tested in fixed test set (first 5 instances)
  test_batch_size: 1
  report: False
  render: False
  num_render_eps: 0
  #strict_max_num: False
  test_env_cfg:
    fixed_dataset: True
    data_file_path: ${data_file_path} # test file depends on env config by default
    # checkpoint_load_path: ${checkpoint_load_path}
  env_kwargs:
    report_on_improvement: False
    construction_args:
      method: 'savings'
    num_steps: ${num_iters}
    acceptance_mode: 'SELECT_EPSILON'
    operator_mode: 'SELECT_LS+' # 'SELECT_LS' # 'SELECT_LS+' # 'SET'
    position_mode: 'ALL'
    mode_args:
      ls_ops: ['TWO_OPT']
      accept_rule: 'BEST_ACCEPT'
      random_shuffle: True
      num_iters: 1
      num_nodes_per_iter: 15
      epsilon: 0.1
      restart_at_step: 16  #8
      restart_mode: "initial"


monitor_cfg: {}
checkpoint_cfg: {}
trainer_cfg: {}
strict_max_num: False