# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: uniform
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/${problem}/${coords_dist}/${problem}${graph_size}/test_seed1234.pkl
checkpoint_load_path: models/NeuroLKH/NeuroLKH/pretrained/neurolkh.pt
normalize_data: True

# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
  sampling_args:
    sample_size: 1024
    graph_size: ${graph_size}