# @package _global_
# policy config

policy: "SA"

policy_cfg:
  first_solutions_strategy: 'AUTOMATIC' # 'SAVINGS', 'SWEEP'--> works for C++ only, 'PATH_CHEAPEST_ARC'
  local_search_strategy: 'SIMULATED_ANNEALING'
  solution_limit: #None
  verbose: False
  log_search: False
  advanced_search: False
  int_prec: 1000


#   # time_limit: ${test_cfg.time_limit} #4
# cvrp50_unf, time_limit: 2
# {'cost_mean': 12.354195502135582, 'cost_std': 1.521527883815267,
#  'num_vehicles_mean': 8.0, 'num_vehicles_std': 0.0, 'num_vehicles_median': 8.0,
#  'run_time_mean': 2.000894856533222, 'run_time_total': 1024.4581665450096, 'num_infeasible': 0}

# cvrp50_unf, time_limit: 4
# {'cost_mean': 12.35432310568288, 'cost_std': 1.5215861836412852,
#  'num_vehicles_mean': 8.0, 'num_vehicles_std': 0.0, 'num_vehicles_median': 8.0,
#  'run_time_mean': 4.00040162122275, 'run_time_total': 2048.205630066048, 'num_infeasible': 0}
