# @package _global_

# tensorboard --host localhost --port 8080 --logdir=./outputs

run_type: "val"
number_runs: 1
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
# cuda: ---> set in policy config (b/c dependent on policy)
# eGPU GeForce RTX 3060 (G3DMark Mark: 17177, G2DMark: 975)
G3DMark: 17177
G2DMark: 975
# DELL Machine (Intel® Core™ i7-10850H - 12 Threads): 11980
# DELL Machine (Intel® Core™ i7-10850H - 1 Threads): 2714
CPU_Mark_single: 2714
CPU_Mark: 11980
number_threads: 12
number_cpus: 6

test_cfg:
  eval_type: ['pi', 'wrap']  # 'simple', 'wrap', 'pi', ['pi', 'wrap']
  time_limit: 10
  save_solutions: False   # either save solution in log dir of run output dir
  save_for_analysis: True #True # or save solutions for further analysis in saved results folder
  saved_res_dir: outputs/saved_results # where results for analysis should be saved
  out_name: ${out_name}
  save_trajectory: True   # will always be saved in log dir of run output dir
  save_traj_for:  # IDs of Instances to plot in list - if None, first instance in dataset is plotted
  fixed_dataset: True
  data_file_path: ${data_file_path}
  dataset_size:  # to overwrite the number of instances to be tested in fixed test set (first 5 instances)
  dataset_range: # solve range of dataset , e.g. [10, 20]

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'

