# @package _global_
# problem args

problem: "tsp"
graph_size: 100
coords_dist: uchoa
out_name: ${problem}_${graph_size}_${coords_dist}
data_file_path: data/test_data/tsp/uchoa/${problem}${graph_size}/val_seed1234_size128.pt
normalize_data: True  # BQ only needs demands normalized - so here we want normalized coords
checkpoint_load_path: models/NeuOpt/NeuOpt/pretrained/tsp100.pt


# RP Env cfg
env_kwargs:
  generator_args:
    coords_sampling_dist: ${coords_dist}
    single_large_instance: # data/train_data/${problem}/${coords_dist}/single_large_instance.pt
    depot_type:  # Depot Position (uchoa only): C = central (500, 500), E = eccentric (0, 0), R = random
    customer_type:  # Customer Position (uchoa only): C = Clustered, RC = Random-Clustered (half half), R = Random
  sampling_args:
    sample_size: 128
    graph_size: ${graph_size}
    subsample: False


# model specific env features
wo_feature1: true # remove VI features
wo_feature3: true # remove ES features