# @package _global_
# policy config

policy: "NeuroLKH"
cuda: True

policy_cfg:
  num_workers: 8
  model_path: ${checkpoint_load_path}
  exe_path: "./models/NeuroLKH/NeuroLKH/LKH"
  max_trials: 10000
  int_prec: 10000
  batch_size: 1  # must be 1

# TIME_LIMIT: ${test_cfg.time_limit}

# cvrp50_unf, max_trials=100, cuda=True:
# {'cost_mean': 11.741642569251809, 'cost_std': 1.4257635060620726,
# 'num_vehicles_mean': 8.0, 'num_vehicles_std': 0.0,
# 'run_time_mean': 0.17586499230080843, 'run_time_total': 90.04287605801392}

# cvrp50_unf, max_trials=1000, cuda=True:
# {'cost_mean': 11.692438628795372, 'cost_std': 1.416603566554201,
# 'num_vehicles_mean': 8.0, 'num_vehicles_std': 0.0, 'num_vehicles_median': 8.0,
# 'run_time_mean': 2.605479807682425, 'run_time_total': 1334.0056615334015, 'num_infeasible': 0}
